name: Release Creation

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Build Module
        run: |
          npm ci
          npm run build

      - name: Extract Version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Modify Module Manifest
        uses: microsoft/variable-substitution@v1
        with:
          files: "./dist/module.json"
        env:
          version: ${{steps.get_version.outputs.version-without-v}}
          manifest: https://github.com/${{github.repository}}/releases/latest/download/module.json
          download: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/module.zip

      - name: Create Module
        working-directory: ./dist
        run: zip -r ./module.zip ./*

      - name: Get Changelog
        uses: release-flow/keep-a-changelog-action@v3
        id: changelog
        with:
          command: query
          version: ${{steps.get_version.outputs.version-without-v}}

      - name: Update Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          allowUpdates: true
          draft: ${{github.event.release.draft}}
          prerelease: ${{github.event.release.prerelease}}
          name: ${{steps.get_version.outputs.version-without-v}}
          body: ${{steps.changelog.outputs.release-notes}}
          artifacts: "./dist/module.json, ./dist/module.zip"
